name: flutter
base: core18
version: git
summary: Flutter
description: |
  Flutter is Google’s UI toolkit for building beautiful, natively compiled
  applications for mobile, web, and desktop from a single codebase.

grade: stable
confinement: strict
architectures:
  - build-on: amd64

layout:
  /usr/share/git-core:
    bind: $SNAP/usr/share/git-core
  /usr/lib/git-core:
    bind: $SNAP/usr/lib/git-core
  /usr/include:
    bind: $SNAP/usr/include
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmvec_nonshared.a:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmvec_nonshared.a
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libc_nonshared.a:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libc_nonshared.a

apps:
  flutter:
    command: flutter.sh
    extensions: [gnome-3-34]
    plugs:
      - home
      - network
      - removable-media
      - adb-support
    environment:
      HOME: $SNAP_USER_COMMON
      CPPFLAGS: '-I${SNAP}/usr/include/'
      LDFLAGS: '-L${SNAP}/gnome-platform/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/ -L${SNAP}/gnome-platform/usr/lib/-L${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/ -L${SNAP}/usr/lib/'
      __EGL_VENDOR_LIBRARY_DIRS: $__EGL_VENDOR_LIBRARY_DIRS:$SNAP/gnome-platform/usr/share/glvnd/egl_vendor.d

parts:
  flutter:
    plugin: nil
    source: .
    override-build: |
      cp flutter.sh $SNAPCRAFT_PART_INSTALL/
    stage-packages:
      - jq
      - git
      - curl
      - unzip
      - clang
      - libstdc++-8-dev
      - make
      - rsync
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxxf86vm1
      - libgl1
      - libx11-6
    prime:
      - -lib32
      - -usr/lib32
      - -usr/lib/llvm-6.0/lib/clang/6.0.0/lib/linux/*i386*

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [flutter]
    plugin: nil
    build-snaps: [core18, gnome-3-34-1804]
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-34-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
