name: flutter
base: core18
version: git
summary: Flutter
description: |
  Flutter is Google’s UI toolkit for building beautiful, natively compiled
  applications for mobile, web, and desktop from a single codebase.

grade: stable
confinement: classic
architectures:
  - build-on: amd64

apps:
  flutter:
    command: flutter.sh
    environment:
      HOME: $SNAP_USER_COMMON
      PATH: ${SNAP}/usr/bin:${SNAP}/bin:$PATH
      CPPFLAGS: '-I${SNAP}/usr/include/c++/8 -I${SNAP}/usr/include'
      LDFLAGS: '-L${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/ -L${SNAP}/usr/lib/'
      PKG_CONFIG_PATH: /snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/lib/pkgconfig:/snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/share/pkgconfig:/snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pkgconfig:$PKG_CONFIG_PATH

parts:
  flutter:
    plugin: nil
    source: .
    override-build: |
      cp flutter.sh $SNAPCRAFT_PART_INSTALL/
    stage-packages:
      - jq
      - xz-utils
      - git
      - curl
      - unzip
      - clang
      - libstdc++-8-dev
      - make
      - rsync

    prime:
      - -lib32
      - -usr/lib32
      - -usr/lib/llvm-6.0/lib/clang/6.0.0/lib/linux/*i386*
      - -usr/share/doc
      - -usr/share/man
