name: flutter
base: core18
version: git
summary: Flutter
description: |
  Flutter is Google’s UI toolkit for building beautiful, natively compiled
  applications for mobile, web, and desktop from a single codebase.

grade: stable
confinement: strict
architectures:
  - build-on: amd64

layout:
  /usr/share/git-core:
    bind: $SNAP/usr/share/git-core
  /usr/lib/git-core:
    bind: $SNAP/usr/lib/git-core
  /usr/include:
    bind: $SNAP/usr/include
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmvec_nonshared.a:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmvec_nonshared.a
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libc_nonshared.a:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libc_nonshared.a

apps:
  flutter:
    command: flutter.sh
    extensions: [gnome-3-28]
    plugs:
      - home
      - network
      - removable-media
      - adb-support
    environment:
      HOME: $SNAP_USER_COMMON
      CPPFLAGS: '-I${SNAP}/usr/include/c++/8 -I${SNAP}/usr/include'
      LDFLAGS: '-L${SNAP}/gnome-platform/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/ -L${SNAP}/gnome-platform/usr/lib/-L${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/ -L${SNAP}/usr/lib/'
      PKG_CONFIG_PATH: /snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/lib/pkgconfig:/snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/share/pkgconfig:/snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pkgconfig
      __EGL_VENDOR_LIBRARY_DIRS: $__EGL_VENDOR_LIBRARY_DIRS:$SNAP/gnome-platform/usr/share/glvnd/egl_vendor.d

parts:
  flutter:
    plugin: nil
    source: .
    override-build: |
      cp flutter.sh $SNAPCRAFT_PART_INSTALL/
    stage-packages:
      - jq
      - xz-utils
      - git
      - curl
      - unzip
      - clang
      - libc6-dev
      - libstdc++-8-dev
      - make
      - pkg-config
      - libgtk-3-dev
      - rsync
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxxf86vm1
      - libgl1
      - libx11-6

    prime:
      - -lib32
      - -usr/lib32
      - -usr/lib/llvm-6.0/lib/clang/6.0.0/lib/linux/*i386*
      - -usr/share/doc
      - -usr/share/man

  # Fix pkgconfig files
  pkgconfig:
    after: [flutter]
    plugin: nil
    override-prime: |
      set -eux
      for PC in $(find . -path "*/pkgconfig/*.pc")
      do
        sed -i 's#prefix=$SNAPCRAFT_STAGE#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current#' $PC
        sed -i 's#prefix = /usr#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#' $PC
        sed -i 's#prefix=/usr#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#' $PC
        sed -i 's#original_prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#original_prefix=/usr#' $PC

        sed -i 's#libdir=/usr#libdir=${prefix}#' $PC
        sed -i 's#libdir=/lib#libdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/lib#' $PC

        sed -i 's#exec_prefix=/usr#exec_prefix=${prefix}#' $PC
        sed -i 's#includedir=/usr#includedir=${prefix}#' $PC
        sed -i 's#sysconfdir=/etc#sysconfdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/etc#' $PC

        sed -i 's#/usr/#/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/#g' $PC
        sed -i 's#/etc/#/snap/$SNAPCRAFT_PROJECT_NAME/current/etc/#g' $PC
      done

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [pkgconfig]
    plugin: nil
    build-snaps: [core18, gnome-3-28-1804]
    override-prime: |
      set -eux
      find . -type d -empty -delete
      for snap in "core18" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
